### ISSUE TITLE
Mixin conflicts with several mods

### ISSUE THREAD

**Issue by florensie** [florensie/swimmies#2]
Heavy usage of redirects creates conflicts with the following mods:
- [ ] The Aether Reborn
- [ ] Random Patches (in aof3)
- [ ] Mouse Wheelie

Should test in big modpacks like AOF to check for more conflicts.

Possible fixes are:
- Fix the conflict on our side
- Fix the conflict on the other mods' side
- Provide a surrogate redirect (if this is possible)

**Comment by riseon** [comment]
As discussed on the Artifacts Issue https://github.com/ochotonida/artifacts/issues/187 reverting CarryOn to version 2.0.2.3 let the game launch

**Comment by florensie** [comment]
I replaced all `@Redirects` a while ago with MixinExtras equivalents, which should be more compatible. See e3f9d9c7.
