### ISSUE TITLE
Clash with chaosawakens

### ISSUE THREAD

**Issue by ghost** [florensie/swimmies#7]
expandability-2.0.1-forge
Artifacts-1.16.5-2.10.5
curios-forge-1.16.5-4.1.0.0
geckolib-forge-1.16.5-3.0.106
chaosawakens-1.16.5-0.11.0.1
[latest.log](https://github.com/florensie/ExpandAbility/files/11573468/latest.log)

**Comment by FanRenLa** [comment]
chaosawakens-1.16.5-0.11.1.2.jar  also conflicts with ExpandAbility

**Comment by RaveTr** [comment]
Issue on our end here at Chaos Awakens, fixed for our next update (codebase rewrite/refactor). You can choose to remove 1 or the other in the meantime.

**Comment by florensie** [comment]
@RaveTr Thanks for figuring this one out!
